<style>
    @media (max-width: 770px)  {
        .navbar-fixed-top{
            margin: 2%; margin-top: -5%;
        }
    }
</style>
<div  class="navbar navbar-fixed-top <?= isset($inverse) ? 'navbar-inverse' : 'navbar-default' ?>" role="navigation">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?=BASE_URL?>"><?= APP_NAME ?></a>
        </div>

        <?php if (isset($menu) && sizeof($menu) > 0): ?>
        <ul class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <?php foreach ($menu as $item): ?>
                    <?php
                    $_item_style = '';

                    if (View::getViewId() && $item['id'] == View::getViewId()) {
                        $_item_style = 'active';
                    }
                    ?>

                    <li class="<?= $_item_style ?>"><a href="<?=$item['enlace']?>"><i
                                    class="<?= $item['imagen'] ?> <?= isset($inverse) ? 'icon-white' : '' ?>"> </i> <?= $item['titulo'] ?>
                        </a></li>
                <?php endforeach; ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a id="registrarse" href="<?=BASE_URL?>usuarios/registro">Registrarse</a></li>
                <?php if (Session::get('autenticado')): ?>
                    <div class="navbar-form pull-right">
                        <a href="<?=BASE_URL?>usuarios/login/cerrar" class="btn btn-danger"><i
                                    class="icon-off icon-white"> </i> Salir</a>
                    </div>
                <?php else: ?>
                    <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown">Iniciar Sesión<strong class="caret"></strong></a>
                        <ul class="dropdown-menu" style="padding: 20px;">
                            <form method="post" action="<?=BASE_URL?>usuarios/login" accept-charset="UTF-8">
                                <input type="hidden" value="1" name="enviar">
                                <input style="padding: 5px;margin: 10px;"  name="usuario" type="text"
                                           placeholder="Usuario">
                                <input style="padding: 5px;margin: 10px;"  name="pass" type="password"
                                           placeholder="Contraseña">
                                <!--
                                <input style="float: left; margin-right: 10px;" type="checkbox" name="remember-me" id="remember-me" value="1">
                                <label class="string optional" for="user_remember_me"> Recordarme</label>
                                -->
                                <input class="btn btn-success btn-block" type="submit" id="sign-in" value="Entrar">
                                <!--                                    <label style="text-align:center;margin-top:5px">o</label>-->
                                <!--                                    <input class="btn btn-danger btn-block" type="button" id="sign-in-google" value="Iniciar con Google">-->
                                <!--                                    <input class="btn btn-primary btn-block" type="button" id="sign-in-twitter" value="Iniciar con Facebook">-->
                            </form>
                        </ul>
                    </li>
                <?php endif; ?>
            </ul>
    </div>
    <?php endif; ?>
</div>