<div class="navbar navbar-fixed-top <?= isset($inverse) ? 'navbar-inverse' : ''?>">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <i class="icon-tasks"></i>
            </a>
            <a class="brand" href="<?=BASE_URL?>"><?=APP_NAME?></a>

            <?php if(isset($menu) && sizeof($menu) > 0): ?>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <?php foreach($menu as $item): ?>
                            <?php 
                            $_item_style = '';
                            
                            if(View::getViewId() && $item['id'] == View::getViewId())
                            {
                                $_item_style = 'active';
                            }
                            ?>

                            <li class="<?=$_item_style?>"><a  href="<?=$item['enlace']?>"><i class="<?=$item['imagen']?> <?=  isset($inverse) ? 'icon-white' : ''?>"> </i> <?=$item['titulo']?></a></li>
                        <?php endforeach; ?>
                    </ul>

                    <?php if(Session::get('autenticado')): ?>
                        <div class="navbar-form pull-right">
                            <a href="<?=BASE_URL?>usuarios/login/cerrar" class="btn btn-danger"><i class="icon-off icon-white"> </i> Salir</a>
                        </div>
                    <?php else: ?>
                        <form class="navbar-form pull-right" method="post" action="<?=BASE_URL?>usuarios/login">
                            <input type="hidden" value="1" name="enviar">
                            <input class="span2" name="usuario" type="text" placeholder="Usuario">
                            <input class="span2" name="pass" type="password" placeholder="Password">
                            <button type="submit" class="btn btn-success"><i class="icon-user icon-white"> </i> Entrar</button>
                        </form>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>