<div class="navbar navbar-fixed-top <?= isset($inverse) ? 'navbar-inverse' : ''?>">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <i class="icon-tasks"></i>
            </a>
            <a class="brand" href="<?=BASE_URL?>"><?=APP_NAME?></a>

            <?php if(isset($menu) && sizeof($menu) > 0): ?>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <?php foreach($menu as $item): ?>
                            <?php 
                            $_item_style = '';
                            
                            if(View::getViewId() && $item['id'] == View::getViewId())
                            {
                                $_item_style = 'active';
                            }
                            ?>

                            <li class="<?=$_item_style?>"><a  href="<?=$item['enlace']?>"><i class="<?=$item['imagen']?> <?=  isset($inverse) ? 'icon-white' : ''?>"> </i> <?=$item['titulo']?></a></li>
                        <?php endforeach; ?>
                    </ul>
                    <ul class="nav pull-right">
                        <li><a id="registrarse" href="<?=BASE_URL?>usuarios/registro">Registrarse</a></li>
                        <li class="divider-vertical"></li>
                        <?php if(Session::get('autenticado')): ?>
                            <div class="navbar-form pull-right">
                                <a href="<?=BASE_URL?>usuarios/login/cerrar" class="btn btn-danger"><i class="icon-off icon-white"> </i> Salir</a>
                            </div>
                        <?php else: ?>
                        <li class="dropdown">
                            <a class="dropdown-toggle" href="#" data-toggle="dropdown">Iniciar Sesi&oacute;n<strong class="caret"></strong></a>
                            <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
                                <form method="post" action="<?=BASE_URL?>usuarios/login" accept-charset="UTF-8" >
                                    <input type="hidden" value="1" name="enviar">
                                    <input style="margin-bottom: 15px;"  name="usuario" type="text" placeholder="Usuario">
                                    <input style="margin-bottom: 15px;" name="pass" type="password" placeholder="Password">
                                    <!--
                                    <input style="float: left; margin-right: 10px;" type="checkbox" name="remember-me" id="remember-me" value="1">
                                    <label class="string optional" for="user_remember_me"> Recordarme</label>
                                    -->
                                    <input class="btn btn-success btn-block" type="submit" id="sign-in" value="Entrar">
                                    <label style="text-align:center;margin-top:5px">o</label>
                                    <input class="btn btn-danger btn-block" type="button" id="sign-in-google" value="Iniciar con Google">
                                    <input class="btn btn-primary btn-block" type="button" id="sign-in-twitter" value="Iniciar con Facebook">
                                </form>
                            </div>
                        </li>
                        <?php endif; ?>
                    </ul>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>